# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designerGUI.ui'
#
# Created: Sun Jan 22 22:26:45 2012
#      by: PyQt4 UI code generator 4.9
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_crawler(object):
    def setupUi(self, crawler):
        crawler.setObjectName(_fromUtf8("crawler"))
        crawler.resize(650, 425)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(crawler.sizePolicy().hasHeightForWidth())
        crawler.setSizePolicy(sizePolicy)
        crawler.setMinimumSize(QtCore.QSize(650, 425))
        crawler.setMaximumSize(QtCore.QSize(650, 425))
        crawler.setFocusPolicy(QtCore.Qt.NoFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/cirno/icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        crawler.setWindowIcon(icon)
        crawler.setStyleSheet(_fromUtf8(""))
        self.tabWidget = QtGui.QTabWidget(crawler)
        self.tabWidget.setGeometry(QtCore.QRect(-3, 0, 661, 431))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777211, 16777215))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_one = QtGui.QWidget()
        self.tab_one.setObjectName(_fromUtf8("tab_one"))
        self.gridLayoutWidget = QtGui.QWidget(self.tab_one)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 0, 511, 411))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.inputGrid = QtGui.QGridLayout(self.gridLayoutWidget)
        self.inputGrid.setMargin(0)
        self.inputGrid.setObjectName(_fromUtf8("inputGrid"))
        self.threadsLabel = QtGui.QLabel(self.gridLayoutWidget)
        self.threadsLabel.setObjectName(_fromUtf8("threadsLabel"))
        self.inputGrid.addWidget(self.threadsLabel, 5, 0, 1, 1)
        self.browseBtn = QtGui.QPushButton(self.gridLayoutWidget)
        self.browseBtn.setObjectName(_fromUtf8("browseBtn"))
        self.inputGrid.addWidget(self.browseBtn, 6, 2, 1, 1)
        self.imageLabel = QtGui.QLabel(self.gridLayoutWidget)
        self.imageLabel.setAcceptDrops(False)
        self.imageLabel.setObjectName(_fromUtf8("imageLabel"))
        self.inputGrid.addWidget(self.imageLabel, 3, 0, 1, 1)
        self.savepathLabel = QtGui.QLabel(self.gridLayoutWidget)
        self.savepathLabel.setAutoFillBackground(False)
        self.savepathLabel.setObjectName(_fromUtf8("savepathLabel"))
        self.inputGrid.addWidget(self.savepathLabel, 6, 0, 1, 1)
        self.imageLimitBox = QtGui.QSpinBox(self.gridLayoutWidget)
        self.imageLimitBox.setMaximumSize(QtCore.QSize(100, 20))
        self.imageLimitBox.setMinimum(0)
        self.imageLimitBox.setMaximum(1000000)
        self.imageLimitBox.setObjectName(_fromUtf8("imageLimitBox"))
        self.inputGrid.addWidget(self.imageLimitBox, 3, 1, 1, 1)
        self.postcountLabel = QtGui.QLabel(self.gridLayoutWidget)
        self.postcountLabel.setObjectName(_fromUtf8("postcountLabel"))
        self.inputGrid.addWidget(self.postcountLabel, 2, 0, 1, 1)
        self.postcountLineEdit = QtGui.QLineEdit(self.gridLayoutWidget)
        self.postcountLineEdit.setReadOnly(True)
        self.postcountLineEdit.setObjectName(_fromUtf8("postcountLineEdit"))
        self.inputGrid.addWidget(self.postcountLineEdit, 2, 1, 1, 1)
        self.threadSpinBox = QtGui.QSpinBox(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.threadSpinBox.sizePolicy().hasHeightForWidth())
        self.threadSpinBox.setSizePolicy(sizePolicy)
        self.threadSpinBox.setMaximumSize(QtCore.QSize(50, 20))
        self.threadSpinBox.setMinimum(1)
        self.threadSpinBox.setMaximum(8)
        self.threadSpinBox.setProperty("value", 4)
        self.threadSpinBox.setObjectName(_fromUtf8("threadSpinBox"))
        self.inputGrid.addWidget(self.threadSpinBox, 5, 1, 1, 1)
        self.tagLineEdit = QtGui.QLineEdit(self.gridLayoutWidget)
        self.tagLineEdit.setObjectName(_fromUtf8("tagLineEdit"))
        self.inputGrid.addWidget(self.tagLineEdit, 0, 1, 1, 1)
        self.booruComboBox = QtGui.QComboBox(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.booruComboBox.sizePolicy().hasHeightForWidth())
        self.booruComboBox.setSizePolicy(sizePolicy)
        self.booruComboBox.setMaximumSize(QtCore.QSize(150, 20))
        self.booruComboBox.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.booruComboBox.setEditable(False)
        self.booruComboBox.setMaxVisibleItems(11)
        self.booruComboBox.setObjectName(_fromUtf8("booruComboBox"))
        self.inputGrid.addWidget(self.booruComboBox, 1, 1, 1, 1)
        self.ratingGrid = QtGui.QGridLayout()
        self.ratingGrid.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.ratingGrid.setObjectName(_fromUtf8("ratingGrid"))
        self.questionableRadio = QtGui.QRadioButton(self.gridLayoutWidget)
        self.questionableRadio.setObjectName(_fromUtf8("questionableRadio"))
        self.ratingGrid.addWidget(self.questionableRadio, 0, 2, 1, 1)
        self.explicitRadio = QtGui.QRadioButton(self.gridLayoutWidget)
        self.explicitRadio.setChecked(True)
        self.explicitRadio.setObjectName(_fromUtf8("explicitRadio"))
        self.ratingGrid.addWidget(self.explicitRadio, 0, 1, 1, 1)
        self.safeRadio = QtGui.QRadioButton(self.gridLayoutWidget)
        self.safeRadio.setObjectName(_fromUtf8("safeRadio"))
        self.ratingGrid.addWidget(self.safeRadio, 0, 3, 1, 1)
        self.inputGrid.addLayout(self.ratingGrid, 4, 1, 1, 1)
        self.savepathLineEdit = QtGui.QLineEdit(self.gridLayoutWidget)
        self.savepathLineEdit.setObjectName(_fromUtf8("savepathLineEdit"))
        self.inputGrid.addWidget(self.savepathLineEdit, 6, 1, 1, 1)
        self.booruLabel = QtGui.QLabel(self.gridLayoutWidget)
        self.booruLabel.setObjectName(_fromUtf8("booruLabel"))
        self.inputGrid.addWidget(self.booruLabel, 1, 0, 1, 1)
        self.tagLabel = QtGui.QLabel(self.gridLayoutWidget)
        self.tagLabel.setObjectName(_fromUtf8("tagLabel"))
        self.inputGrid.addWidget(self.tagLabel, 0, 0, 1, 1)
        self.ratingLabel = QtGui.QLabel(self.gridLayoutWidget)
        self.ratingLabel.setAcceptDrops(False)
        self.ratingLabel.setObjectName(_fromUtf8("ratingLabel"))
        self.inputGrid.addWidget(self.ratingLabel, 4, 0, 1, 1)
        self.outputTextEdit = QtGui.QTextEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputTextEdit.sizePolicy().hasHeightForWidth())
        self.outputTextEdit.setSizePolicy(sizePolicy)
        self.outputTextEdit.setMaximumSize(QtCore.QSize(600, 100))
        self.outputTextEdit.setAutoFillBackground(False)
        self.outputTextEdit.setFrameShape(QtGui.QFrame.Panel)
        self.outputTextEdit.setFrameShadow(QtGui.QFrame.Plain)
        self.outputTextEdit.setReadOnly(True)
        self.outputTextEdit.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.outputTextEdit.setObjectName(_fromUtf8("outputTextEdit"))
        self.inputGrid.addWidget(self.outputTextEdit, 7, 0, 1, 2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.crawlBtn = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.crawlBtn.sizePolicy().hasHeightForWidth())
        self.crawlBtn.setSizePolicy(sizePolicy)
        self.crawlBtn.setObjectName(_fromUtf8("crawlBtn"))
        self.verticalLayout.addWidget(self.crawlBtn)
        self.cancelBtn = QtGui.QPushButton(self.gridLayoutWidget)
        self.cancelBtn.setObjectName(_fromUtf8("cancelBtn"))
        self.verticalLayout.addWidget(self.cancelBtn)
        self.inputGrid.addLayout(self.verticalLayout, 7, 2, 1, 1)
        self.postcountBtn = QtGui.QPushButton(self.gridLayoutWidget)
        self.postcountBtn.setObjectName(_fromUtf8("postcountBtn"))
        self.inputGrid.addWidget(self.postcountBtn, 2, 2, 1, 1)
        self.cirnoLogo = QtGui.QWidget(self.tab_one)
        self.cirnoLogo.setGeometry(QtCore.QRect(520, 70, 151, 251))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cirnoLogo.sizePolicy().hasHeightForWidth())
        self.cirnoLogo.setSizePolicy(sizePolicy)
        self.cirnoLogo.setMinimumSize(QtCore.QSize(0, 0))
        self.cirnoLogo.setMaximumSize(QtCore.QSize(100000, 100000))
        self.cirnoLogo.setBaseSize(QtCore.QSize(0, 0))
        self.cirnoLogo.setStyleSheet(_fromUtf8("image: url(:/cirno/cirno3.png);"))
        self.cirnoLogo.setObjectName(_fromUtf8("cirnoLogo"))
        self.tabWidget.addTab(self.tab_one, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.cirnoLogo2 = QtGui.QWidget(self.tab_2)
        self.cirnoLogo2.setGeometry(QtCore.QRect(480, 0, 171, 191))
        self.cirnoLogo2.setStyleSheet(_fromUtf8("image: url(:/cirno/cirno3.png);"))
        self.cirnoLogo2.setObjectName(_fromUtf8("cirnoLogo2"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.tab_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 280, 611, 80))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.cachepathLabel = QtGui.QLabel(self.horizontalLayoutWidget)
        self.cachepathLabel.setObjectName(_fromUtf8("cachepathLabel"))
        self.horizontalLayout_4.addWidget(self.cachepathLabel)
        self.cachepathLineEdit = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.cachepathLineEdit.setObjectName(_fromUtf8("cachepathLineEdit"))
        self.horizontalLayout_4.addWidget(self.cachepathLineEdit)
        self.cachepathFileDialog = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.cachepathFileDialog.setObjectName(_fromUtf8("cachepathFileDialog"))
        self.horizontalLayout_4.addWidget(self.cachepathFileDialog)
        self.cacheBtn = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.cacheBtn.setObjectName(_fromUtf8("cacheBtn"))
        self.horizontalLayout_4.addWidget(self.cacheBtn)
        self.settingscancelBtn = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.settingscancelBtn.setObjectName(_fromUtf8("settingscancelBtn"))
        self.horizontalLayout_4.addWidget(self.settingscancelBtn)
        self.gridLayoutWidget_3 = QtGui.QWidget(self.tab_2)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(20, 200, 611, 80))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.booruShorthand = QtGui.QLineEdit(self.gridLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.booruShorthand.sizePolicy().hasHeightForWidth())
        self.booruShorthand.setSizePolicy(sizePolicy)
        self.booruShorthand.setObjectName(_fromUtf8("booruShorthand"))
        self.gridLayout.addWidget(self.booruShorthand, 0, 1, 1, 1)
        self.defaultSavePathLabel = QtGui.QLabel(self.gridLayoutWidget_3)
        self.defaultSavePathLabel.setObjectName(_fromUtf8("defaultSavePathLabel"))
        self.gridLayout.addWidget(self.defaultSavePathLabel, 1, 2, 1, 1)
        self.defaultSavePath = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.defaultSavePath.setObjectName(_fromUtf8("defaultSavePath"))
        self.gridLayout.addWidget(self.defaultSavePath, 1, 3, 1, 1)
        self.booruLogin = QtGui.QLineEdit(self.gridLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.booruLogin.sizePolicy().hasHeightForWidth())
        self.booruLogin.setSizePolicy(sizePolicy)
        self.booruLogin.setObjectName(_fromUtf8("booruLogin"))
        self.gridLayout.addWidget(self.booruLogin, 1, 1, 1, 1)
        self.booruPasswordLabel = QtGui.QLabel(self.gridLayoutWidget_3)
        self.booruPasswordLabel.setObjectName(_fromUtf8("booruPasswordLabel"))
        self.gridLayout.addWidget(self.booruPasswordLabel, 2, 0, 1, 1)
        self.booruPassword = QtGui.QLineEdit(self.gridLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.booruPassword.sizePolicy().hasHeightForWidth())
        self.booruPassword.setSizePolicy(sizePolicy)
        self.booruPassword.setObjectName(_fromUtf8("booruPassword"))
        self.gridLayout.addWidget(self.booruPassword, 2, 1, 1, 1)
        self.booruLoginLabel = QtGui.QLabel(self.gridLayoutWidget_3)
        self.booruLoginLabel.setObjectName(_fromUtf8("booruLoginLabel"))
        self.gridLayout.addWidget(self.booruLoginLabel, 1, 0, 1, 1)
        self.defaultBooru = QtGui.QLineEdit(self.gridLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.defaultBooru.sizePolicy().hasHeightForWidth())
        self.defaultBooru.setSizePolicy(sizePolicy)
        self.defaultBooru.setObjectName(_fromUtf8("defaultBooru"))
        self.gridLayout.addWidget(self.defaultBooru, 2, 3, 1, 1)
        self.booruShorthandLabel = QtGui.QLabel(self.gridLayoutWidget_3)
        self.booruShorthandLabel.setObjectName(_fromUtf8("booruShorthandLabel"))
        self.gridLayout.addWidget(self.booruShorthandLabel, 0, 0, 1, 1)
        self.defaultBooruLabel = QtGui.QLabel(self.gridLayoutWidget_3)
        self.defaultBooruLabel.setObjectName(_fromUtf8("defaultBooruLabel"))
        self.gridLayout.addWidget(self.defaultBooruLabel, 2, 2, 1, 1)
        self.defaultPathBtn = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.defaultPathBtn.setObjectName(_fromUtf8("defaultPathBtn"))
        self.gridLayout.addWidget(self.defaultPathBtn, 1, 4, 1, 1)
        self.pushButton = QtGui.QPushButton(self.gridLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout.addWidget(self.pushButton, 0, 3, 1, 1)
        self.label = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 2, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))

        self.retranslateUi(crawler)
        self.tabWidget.setCurrentIndex(0)
        self.booruComboBox.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(crawler)

    def retranslateUi(self, crawler):
        crawler.setWindowTitle(QtGui.QApplication.translate("crawler", "CirnoCrawler", None, QtGui.QApplication.UnicodeUTF8))
        self.threadsLabel.setText(QtGui.QApplication.translate("crawler", "     Threads:", None, QtGui.QApplication.UnicodeUTF8))
        self.browseBtn.setText(QtGui.QApplication.translate("crawler", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.imageLabel.setToolTip(QtGui.QApplication.translate("crawler", "Max number of images per page.", None, QtGui.QApplication.UnicodeUTF8))
        self.imageLabel.setText(QtGui.QApplication.translate("crawler", "Image Limit:", None, QtGui.QApplication.UnicodeUTF8))
        self.savepathLabel.setToolTip(QtGui.QApplication.translate("crawler", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Change location to save files to.</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Default is %sysdrive%/Users/%user%/Downloads/%tag%/ for windows,</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">or /home/%tag%/ for unix.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.savepathLabel.setText(QtGui.QApplication.translate("crawler", "      Save to:", None, QtGui.QApplication.UnicodeUTF8))
        self.postcountLabel.setToolTip(QtGui.QApplication.translate("crawler", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Total number of images on a given imageboard for a certain tag.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.postcountLabel.setText(QtGui.QApplication.translate("crawler", "       Count:", None, QtGui.QApplication.UnicodeUTF8))
        self.postcountLineEdit.setPlaceholderText(QtGui.QApplication.translate("crawler", "Number of images for a given tag on selected booru (press count)", None, QtGui.QApplication.UnicodeUTF8))
        self.tagLineEdit.setPlaceholderText(QtGui.QApplication.translate("crawler", "tags go here...", None, QtGui.QApplication.UnicodeUTF8))
        self.questionableRadio.setText(QtGui.QApplication.translate("crawler", "Questionable    ", None, QtGui.QApplication.UnicodeUTF8))
        self.explicitRadio.setText(QtGui.QApplication.translate("crawler", "Explicit", None, QtGui.QApplication.UnicodeUTF8))
        self.safeRadio.setText(QtGui.QApplication.translate("crawler", "Safe", None, QtGui.QApplication.UnicodeUTF8))
        self.booruLabel.setToolTip(QtGui.QApplication.translate("crawler", "Choice of imageboard to download from.", None, QtGui.QApplication.UnicodeUTF8))
        self.booruLabel.setText(QtGui.QApplication.translate("crawler", "         Booru:", None, QtGui.QApplication.UnicodeUTF8))
        self.tagLabel.setToolTip(QtGui.QApplication.translate("crawler", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Tags to download.  Maximum of two. Separate by space and</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\"> wrap in quotes &quot;&quot; to use two tags.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tagLabel.setText(QtGui.QApplication.translate("crawler", "          Tags:", None, QtGui.QApplication.UnicodeUTF8))
        self.ratingLabel.setToolTip(QtGui.QApplication.translate("crawler", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">This is the rating exclusion system. Checking a rating will prevent anything</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\"> of a more risque nature than chosen from being shown.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.ratingLabel.setText(QtGui.QApplication.translate("crawler", "Rating Limit:", None, QtGui.QApplication.UnicodeUTF8))
        self.crawlBtn.setText(QtGui.QApplication.translate("crawler", "Crawl", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelBtn.setText(QtGui.QApplication.translate("crawler", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.postcountBtn.setText(QtGui.QApplication.translate("crawler", "Count", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_one), QtGui.QApplication.translate("crawler", "Crawler", None, QtGui.QApplication.UnicodeUTF8))
        self.cachepathLabel.setText(QtGui.QApplication.translate("crawler", "Cache Path:", None, QtGui.QApplication.UnicodeUTF8))
        self.cachepathFileDialog.setText(QtGui.QApplication.translate("crawler", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.cacheBtn.setText(QtGui.QApplication.translate("crawler", "Cache", None, QtGui.QApplication.UnicodeUTF8))
        self.settingscancelBtn.setText(QtGui.QApplication.translate("crawler", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultSavePathLabel.setText(QtGui.QApplication.translate("crawler", "Default Save Path:", None, QtGui.QApplication.UnicodeUTF8))
        self.booruPasswordLabel.setText(QtGui.QApplication.translate("crawler", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self.booruLoginLabel.setText(QtGui.QApplication.translate("crawler", "Login:", None, QtGui.QApplication.UnicodeUTF8))
        self.booruShorthandLabel.setText(QtGui.QApplication.translate("crawler", "Booru:", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultBooruLabel.setText(QtGui.QApplication.translate("crawler", "Default Booru:", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultPathBtn.setText(QtGui.QApplication.translate("crawler", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("crawler", "Rebuild", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("crawler", "Rebuild TagDB:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("crawler", "Settings", None, QtGui.QApplication.UnicodeUTF8))

import cirnocrawler_rc
